name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: Build prod env
      run: npm run build:prod
    - uses: actions/upload-artifact@v2
      with:
        name: log2orchestra-prod
        path: build
